# -*- coding: utf-8 -*-
"""Minor project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_jRNCLTkc3fDCw8l6oCT4vIp6EkoV_pw
"""

#data - 'https://raw.githubusercontent.com/ameenmanna8824/DATASETS/main/CarPrice_Assignment.csv'

#create a dataframe
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/ameenmanna8824/DATASETS/main/CarPrice_Assignment.csv')
df

df.info()

df.size

df.shape

df['drivewheel'].value_counts()

df['fuelsystem'].value_counts()

df['enginelocation'].value_counts()

df.describe()

df['citympg'].value_counts()

df['highwaympg'].value_counts()

df['enginetype'].value_counts()

df['boreratio'].value_counts()

